site_name: TotMaxim site
site_url: http://127.0.0.1:8000/simple-mkdocs-site/shell/
theme:
  name: material
  palette:
    scheme: default
    toggle:
      icon: material/moon
      name: Switch to dark mode
nav:
  - Не игра: shell.md
  - Игра: game.md
  - CICD: CICD/cicd.md

site_author: Maxim Maxim
copyright: Maxim, totmaxim, 2024
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences